# Generated by Django 4.1.5 on 2023-01-28 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_collection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='name',
            new_name='title',
        ),
    ]
